[package]
name = "inky-2048"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
env_logger = "0.9"
libremarkable = "0.5"
log = "0.4"
play-2048 = "1"
